AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Exclude:
    - lib/orderable/executors/**/*

Metrics/ClassLength:
  Exclude:
    - lib/orderable/executor.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - orderable.gemspec

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false
