development:
  adapter: postgresql
  database: orderable_development
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
