name: Code test coverage badge
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage:
    name: Test suite for coverage
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
      percentage_coverage: ${{ steps.coverage.outputs.percentage_coverage }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      SCHEMA: structure.sql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec -fd

      - name: Save code coverage
        id: coverage
        run: |
          COVERAGE="$( cat ./coverage/.last_run.json | grep "line" | grep -oE "[0-9]+\.[0-9]+" )"
          echo "##[set-output name=coverage;]${COVERAGE}"
          echo "##[set-output name=percentage_coverage;]${COVERAGE}%"

  badge:
    name: Generate badge image and deply to GitHub Pages
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create directory for badge
        run: |
          mkdir ./badge

      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.2
        id: badge
        with:
          label: 'Coverage'
          status: ${{ needs.coverage.outputs.percentage_coverage }}
          color: ${{
            needs.coverage.outputs.coverage > 90 && 'green'              ||
            needs.coverage.outputs.coverage > 80 && 'yellow,green'       ||
            needs.coverage.outputs.coverage > 70 && 'yellow'             ||
            needs.coverage.outputs.coverage > 60 && 'orange,yellow'      ||
            needs.coverage.outputs.coverage > 50 && 'orange'             ||
            needs.coverage.outputs.coverage > 40 && 'red,orange'         ||
            needs.coverage.outputs.coverage > 30 && 'red,red,orange'     ||
            needs.coverage.outputs.coverage > 20 && 'red,red,red,orange' ||
            'red' }}
          path: ./badge/test-coverage.svg

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./badge
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
    

