name: Pull request workflow
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    name: Test suite and coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0']
        gemfile: ['gemfiles/activerecord_5.0.2.gemfile', 
        'gemfiles/activerecord_5.1.0.gemfile', 
        # 'gemfiles/activerecord_5.2.2.gemfile', 
        # 'gemfiles/activerecord_6.0.0.gemfile', 
        # 'gemfiles/activerecord_6.1.0.gemfile', 
        'gemfiles/activerecord_main.gemfile']
        # include:
        #   - gemfile: 'gemfiles/activerecord_7.0.0.gemfile'
        #     ruby: '3.1'
        #   - gemfile: 'gemfiles/activerecord_7.0.0.gemfile'
        #     ruby: '3.0'
        #   - gemfile: 'gemfiles/activerecord_6.1.0.gemfile'
        #     ruby: '3.1'
        #   - gemfile: 'gemfiles/activerecord_6.1.0.gemfile'
        #     ruby: '3.0'
        exclude:
          - gemfile: 'gemfiles/activerecord_5.2.2.gemfile'
            ruby: '3.0' # rails 5.2 can't run on ruby 3.0
          - gemfile: 'gemfiles/activerecord_5.1.0.gemfile'
            ruby: '3.0' # rails 5.1 can't run on ruby 3.0
          - gemfile: 'gemfiles/activerecord_5.0.2.gemfile'
            ruby: '3.0' # rails 5.0 can't run on ruby 3.0
          - gemfile: 'gemfiles/activerecord_5.0.2.gemfile'
            ruby: '3.0' # rails 5.0 can't run on ruby 3.0
          - gemfile: 'gemfiles/activerecord_main.gemfile'
            ruby: '2.6' # rails 7+ requires ruby 3.0+
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      SPEC_DISABLE_DROP_DATABASE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec -fd
